### ISSUE TITLE
I'm new to 

### ISSUE THREAD

**Issue by DiMatador** [argyleink/transition.css#23]
hello there! i'm very new to this and i'm having a hard time getting it to work. i'm assuming that this requires javaScript to work?
if yes i have not a clue about javaScript so its out of my league. if that is that case thank you anyways and i'll be back once i know some javaScript. great work

**Comment by argyleink** [comment]
hi! no javascript required 👍🏻 

step 1 is to link to the transition.css stylesheet in your html `<link rel="stylesheet" href="https://unpkg.com/transition-style">`
step 2 is to use attributes on your html elements like `transition-style="in:wipe:up"`

you only need javascript if you want to toggle transitions or go through many different kinds in a row. otherwise, add an attribute, watch it transition. 

hope you get goin and this was helpful! feel free to comment more if things are tough 👍🏻
