### ISSUE TITLE
Random pixelated transition

### ISSUE THREAD

**Issue by ThermScissorpunch** [argyleink/transition.css#28]
Something like this, but then for a transition :)
https://www.youtube.com/watch?v=ois8ipBUgfk

**Comment by argyleink** [comment]
oo nice, i like pixel transitions! the effect in that demo uses an image / pixels to do the effect, and `clip-path` is all vector based.. i'm going to close since I dont think a vector tool will make for an easy to manage pixel effect. but, it'll still be here in the archive if someone comes up with a clever way.
